# Generated by Django 4.2.14 on 2025-07-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
